### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by ghost** [flipswitchingmonkey/houdini_PRTROP#1] opened 2017-12-05 17:54 UTC
I can't see in "ropnet" houdini 16.5 prt exporter

**Comment by flipswitchingmonkey** [comment] 2017-12-05 18:06
yes, it's a bug :(

the problem is that hcustom is linking the dll to the debug versions of hboost - resulting in also looking for msvcp140d.dll instead of msvcp140.dll (notice the missing "d"). that's the debug version of the msvc runtime library. those are only on your system if you have the ms windows SDK installed.

i'll open a ticket with sidefx to see if there's something I can do to force the release versions instead.

**Comment by flipswitchingmonkey** [comment] 2017-12-05 18:29
Check the release section please. I've attached the debug DLLs it is looking for. Those need to be copied to 

    c:\Program Files\Side Effects Software\Houdini 16.5.268\bin\ 

Hopefully that fixes the issue for the moment...

**Comment by Hechton** [comment] 2017-12-05 19:33
thank for files, this is working

**Comment by flipswitchingmonkey** [comment] 2017-12-06 10:47
Fixed in latest release. Works with 16.5.238 as well.

**Closed as completed by flipswitchingmonkey** 2017-12-06 10:47 UTC
